const $=s=>document.querySelector(s);const state={user:null,view:'dashboard',conversations:[],active:null,messages:[],students:[],groups:[],classroom:null,busy:false,image:false,adminLogin:false};
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...options.headers}});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data}
const get=(action,params={})=>api('/api/app?'+new URLSearchParams({action,...params}));const post=(action,data)=>api('/api/app',{method:'POST',body:JSON.stringify({action,...data})});
function notice(message){const el=$('#notice');if(el)el.textContent=message;else alert(message)}
function openMenu(on){$('#sidebar').classList.toggle('open',on);$('#scrim').classList.toggle('show',on)}
$('#menu').onclick=()=>openMenu(true);$('#scrim').onclick=()=>openMenu(false);$('#dashboardShortcut').onclick=()=>navigate('dashboard');
$('#studentTab').onclick=()=>toggleLogin(false);$('#adminTab').onclick=()=>toggleLogin(true);function toggleLogin(admin){state.adminLogin=admin;$('#studentFields').hidden=admin;$('#adminFields').hidden=!admin;$('#studentTab').classList.toggle('selected',!admin);$('#adminTab').classList.toggle('selected',admin);$('#authError').textContent=''}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='';try{const body=state.adminLogin?{action:'admin',email:$('#email').value.trim(),password:$('#password').value}:{action:'student',code:$('#code').value.trim()};const data=await api('/api/session',{method:'POST',body:JSON.stringify(body)});state.user=data.user;start()}catch(err){$('#authError').textContent=err.message}};
$('#logout').onclick=async()=>{await api('/api/session',{method:'POST',body:JSON.stringify({action:'logout'})});state.user=null;state.conversations=[];state.messages=[];$('#app').hidden=true;$('#auth').hidden=false};
async function boot(){try{const {user}=await api('/api/session');if(user){state.user=user;start()}else $('#auth').hidden=false}catch(err){$('#auth').hidden=false;$('#authError').textContent=err.message}}boot();
async function start(){$('#auth').hidden=true;$('#app').hidden=false;$('#userName').textContent=state.user.name;$('#userRole').textContent=state.user.role==='admin'?'Instructor':state.user.group==='grades12'?'Grades 1–2':'Grades 3–5';$('#avatar').textContent=state.user.name[0]?.toUpperCase()||'A';navigate(state.user.role==='admin'?'dashboard':'chat')}
const items=()=>state.user.role==='admin'?[['dashboard','▦','Dashboard'],['chat','✦','AI Chat'],['students','♙','Students'],['groups','◫','Groups'],['activity','◷','Conversations'],['classroom','▣','Classroom'],['settings','⚙','Settings']]:[['chat','✦','AI Chat'],['history','◷','Conversations']];
function navigation(){const nav=$('#navigation');nav.innerHTML=items().map(([id,icon,label])=>`<button class="nav-item ${state.view===id?'active':''}" data-view="${id}"><span>${icon}</span>${label}</button>`).join('');nav.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view))}
async function navigate(view){state.view=view;openMenu(false);navigation();$('#pageTitle').textContent=items().find(i=>i[0]===view)?.[2]||'AI360';$('#dashboardShortcut').hidden=state.user.role!=='admin'||view==='dashboard';$('#content').innerHTML='<div class="loading">Loading…</div>';try{if(view==='dashboard')await dashboard();if(view==='chat')await chat();if(view==='history'||view==='activity')await activity();if(view==='students')await students();if(view==='groups')await groups();if(view==='classroom')await classroom();if(view==='settings')settings()}catch(err){$('#content').innerHTML=`<div class="page"><div class="panel error">${escape(err.message)}</div></div>`}}
async function loadConversations(){state.conversations=(await get('conversations')).conversations}
async function dashboard(){const [s,g,c]=await Promise.all([get('students'),get('groups'),get('conversations')]);state.students=s.students;state.groups=g.groups;state.conversations=c.conversations;$('#content').innerHTML=`<div class="page"><div class="hero"><div class="eyebrow">INSTRUCTOR WORKSPACE</div><h1>Welcome back, Hanin.</h1><p>Keep your club organized and your students' ideas moving.</p><button class="primary" data-go="chat">Open your AI assistant →</button></div><div class="stats"><div class="stat"><strong>${state.students.filter(x=>x.active).length}</strong><span>Active students</span></div><div class="stat"><strong>${state.groups.length}</strong><span>Groups</span></div><div class="stat"><strong>${state.conversations.filter(x=>x.owner_role==='student').length}</strong><span>Student conversations</span></div></div><h2>Workspace</h2><div class="cards">${[['students','Students','Add students and manage access'],['activity','Conversations','Review questions and AI responses'],['classroom','Classroom','Share a live prompt on the projector'],['groups','Groups','Organize by grade level']].map(([id,title,desc])=>`<button class="feature" data-go="${id}"><b>${title} ↗</b><span>${desc}</span></button>`).join('')}</div></div>`;bindGo()}
function bindGo(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go))}
function listConversations(){return state.conversations.filter(c=>c.owner_role===state.user.role&&c.owner_id===state.user.id)}
async function chat(){await loadConversations();state.active=null;state.messages=[];renderChat()}
function renderChat(){const own=listConversations();$('#content').innerHTML=`<div class="chat-layout"><div class="chat-rail"><button id="newChat" class="primary wide">＋ New chat</button><div class="section-label">YOUR CONVERSATIONS</div><div id="chatList">${own.map(c=>`<button class="chat-link ${c.id===state.active?'active':''}" data-id="${c.id}">${escape(c.title)}</button>`).join('')||'<p class="muted">No chats yet.</p>'}</div></div><div class="chat-main"><div id="chatMessages" class="chat-messages">${state.messages.length?state.messages.map(messageHtml).join(''):`<div class="chat-welcome"><div class="spark">✦</div><h1>What can I help with?</h1><p>Ask a question, work through an idea, or create an image.</p></div>`}</div><div class="composer-area"><form id="composer" class="composer"><textarea id="prompt" rows="1" placeholder="Message AI360" aria-label="Message AI360"></textarea><div class="compose-actions"><button id="imageToggle" type="button" class="chip ${state.image?'on':''}">◉ &nbsp;${state.image?'Create image on':'Create image'}</button><button id="send" class="send" type="submit" aria-label="Send">↑</button></div></form><small>AI can make mistakes. Check important information and keep personal details private.</small><div id="notice" role="status"></div></div></div></div>`;
 $('#newChat').onclick=()=>{state.active=null;state.messages=[];state.image=false;renderChat()};document.querySelectorAll('.chat-link').forEach(b=>b.onclick=async()=>{state.active=b.dataset.id;state.messages=(await get('messages',{conversationId:state.active})).messages;renderChat()});$('#imageToggle').onclick=()=>{state.image=!state.image;$('#imageToggle').classList.toggle('on',state.image);$('#imageToggle').textContent=state.image?'◉  Create image on':'◉  Create image'};$('#composer').onsubmit=sendMessage;$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#composer').requestSubmit()}};paintMessages()}
function messageHtml(m){return `<div class="message ${m.role}">${m.role==='assistant'?'<div class="ai-mark">✦</div>':''}<div class="bubble"><div class="text"></div>${m.image_url?`<img alt="AI generated image" class="generated" src="/api/image?path=${encodeURIComponent(m.image_url)}">`:''}</div></div>`}
function paintMessages(){const rows=$('#chatMessages').querySelectorAll('.message');rows.forEach((row,i)=>row.querySelector('.text').textContent=state.messages[i].content);scrollMessages()}
function scrollMessages(){const el=$('#chatMessages');if(el)requestAnimationFrame(()=>el.scrollTop=el.scrollHeight)}
async function sendMessage(e){e.preventDefault();if(state.busy)return;const prompt=$('#prompt').value.trim();if(!prompt)return;state.busy=true;const image=state.image;state.messages.push({role:'user',content:prompt});$('#chatMessages').innerHTML=state.messages.map(messageHtml).join('')+'<div class="loading" id="waiting">AI360 is thinking…</div>';paintMessages();$('#prompt').value='';$('#send').disabled=true;try{const data=await api('/api/chat',{method:'POST',body:JSON.stringify({message:prompt,conversationId:state.active,wantsImage:image})});state.active=data.conversationId;state.messages.push({role:'assistant',content:data.text,image_url:data.imagePath});await loadConversations();state.image=false;renderChat();paintMessages()}catch(err){state.messages.pop();renderChat();paintMessages();$('#prompt').value=prompt;notice(err.message)}finally{state.busy=false;const send=$('#send');if(send)send.disabled=false}}
async function activity(){await loadConversations();const admin=state.user.role==='admin';if(admin){const s=await get('students');state.students=s.students}const rows=admin?state.conversations.filter(c=>c.owner_role==='student'):listConversations();$('#content').innerHTML=`<div class="page"><div class="page-head"><div><h1>${admin?'Student activity':'Your conversations'}</h1><p>${admin?'Review student questions and assistant replies.':'Return to earlier ideas and questions.'}</p></div></div><div class="panel"><div class="table-wrap"><table><thead><tr>${admin?'<th>Student</th>':''}<th>Conversation</th><th>Updated</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr>${admin?`<td>${escape(state.students.find(s=>s.id===c.owner_id)?.name||'Former student')}</td>`:''}<td>${escape(c.title)}</td><td>${new Date(c.updated_at).toLocaleString()}</td><td><button class="text-button" data-review="${c.id}">View →</button></td></tr>`).join('')||'<tr><td colspan="4" class="muted">No conversations yet.</td></tr>'}</tbody></table></div></div><div id="review"></div></div>`;document.querySelectorAll('[data-review]').forEach(b=>b.onclick=async()=>{const {messages}=await get('messages',{conversationId:b.dataset.review});const panel=$('#review');panel.innerHTML=`<div class="panel review"><div class="page-head"><h2>Conversation</h2><button class="subtle" id="closeReview">Close</button></div><div id="reviewMessages">${messages.map(m=>`<div class="review-message"><b>${m.role==='user'?'Student':'AI360'}</b><p></p>${m.image_url?`<img class="generated" src="/api/image?path=${encodeURIComponent(m.image_url)}" alt="Generated image">`:''}</div>`).join('')}</div></div>`;panel.querySelectorAll('.review-message p').forEach((p,i)=>p.textContent=messages[i].content);$('#closeReview').onclick=()=>panel.innerHTML='';panel.scrollIntoView({behavior:'smooth'})})}
async function students(){const [s,g]=await Promise.all([get('students'),get('groups')]);state.students=s.students;state.groups=g.groups;$('#content').innerHTML=`<div class="page"><div class="page-head"><div><h1>Students</h1><p>Create a private code for each student and assign a group.</p></div></div><div class="panel"><h2>Add student</h2><form id="studentForm" class="inline-form"><label>Name<input id="studentName" required maxlength="80" placeholder="Student name"></label><label>Group<select id="studentGroup">${g.groups.map(x=>`<option value="${x.id}">${escape(x.name)}</option>`).join('')}</select></label><button class="primary">Create code</button></form><div id="newCode" class="code-result" hidden></div><p id="notice" role="status" class="error"></p></div><div class="panel"><h2>Student roster</h2><div class="table-wrap"><table><thead><tr><th>Name</th><th>Group</th><th>Status</th><th>Access</th></tr></thead><tbody>${s.students.map(x=>`<tr><td>${escape(x.name)}</td><td><select data-group="${x.id}">${g.groups.map(y=>`<option value="${y.id}" ${y.id===x.group_id?'selected':''}>${escape(y.name)}</option>`).join('')}</select></td><td>${x.active?'Active':'Paused'}</td><td><button class="text-button" data-toggle="${x.id}">${x.active?'Pause':'Restore'}</button></td></tr>`).join('')||'<tr><td colspan="4" class="muted">No students yet.</td></tr>'}</tbody></table></div></div></div>`;$('#studentForm').onsubmit=async e=>{e.preventDefault();try{const {code}=await post('addStudent',{name:$('#studentName').value,groupId:$('#studentGroup').value});await students();$('#newCode').hidden=false;$('#newCode').textContent=`Student code: ${code} — copy and give it to the student now. It is shown only once.`}catch(err){notice(err.message)}};document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async()=>{const x=state.students.find(s=>s.id===b.dataset.toggle);try{await post('updateStudent',{id:x.id,groupId:x.group_id,active:!x.active});students()}catch(err){notice(err.message)}});document.querySelectorAll('[data-group]').forEach(s=>s.onchange=async()=>{const x=state.students.find(x=>x.id===s.dataset.group);try{await post('updateStudent',{id:x.id,groupId:s.value,active:x.active});students()}catch(err){notice(err.message)}})}
async function groups(){state.groups=(await get('groups')).groups;$('#content').innerHTML=`<div class="page"><div class="page-head"><div><h1>Groups</h1><p>Explanation complexity follows each student's assigned grade level.</p></div></div><div class="cards">${state.groups.map(g=>`<div class="panel"><h2>${escape(g.name)}</h2><p>${g.grade_level==='grades12'?'Grades 1–2':'Grades 3–5'}</p></div>`).join('')}</div><div class="panel"><h2>Create a group</h2><form id="groupForm" class="inline-form"><label>Name<input id="groupName" required maxlength="80" placeholder="Group name"></label><label>Grade level<select id="grade"><option value="grades12">Grades 1–2</option><option value="grades35">Grades 3–5</option></select></label><button class="primary">Add group</button></form><p id="notice" class="error"></p></div></div>`;$('#groupForm').onsubmit=async e=>{e.preventDefault();try{await post('addGroup',{name:$('#groupName').value,gradeLevel:$('#grade').value});groups()}catch(err){notice(err.message)}}}
async function classroom(){state.classroom=(await get('classroom')).classroom;const c=state.classroom;$('#content').innerHTML=`<div class="page"><div class="page-head"><div><h1>Classroom</h1><p>Present a shared question or activity on a projector.</p></div><button id="project" class="primary">Open projector ↗</button></div><div class="panel"><h2>Live display</h2><form id="classForm"><label>Title<input id="classTitle" maxlength="120" value="${escape(c.title)}"></label><label>Prompt or instructions<textarea id="classPrompt" rows="6" maxlength="2000"></textarea></label><button class="primary">Publish to projector</button><p id="notice" role="status"></p></form></div></div>`;$('#classPrompt').value=c.prompt;$('#classForm').onsubmit=async e=>{e.preventDefault();try{await post('classroom',{title:$('#classTitle').value,prompt:$('#classPrompt').value});notice('Projector updated.')}catch(err){notice(err.message)}};$('#project').onclick=()=>window.open('/projector.html','ai360-projector')}
function settings(){$('#content').innerHTML=`<div class="page"><div class="page-head"><h1>Settings</h1></div><div class="panel"><h2>Instructor account</h2><p>Signed in as ${escape(state.user.name)}. Instructor access is restricted to the configured Supabase account.</p><p>Student codes are shown only when created. Pause a student to revoke their access.</p></div><div class="panel"><h2>Privacy</h2><p>Conversations and generated images are stored privately. Students see only their own conversations; the instructor can review student activity.</p></div></div>`}
