const SKEY='ai360_pro_v2';let current='';let imageNext=false;let busy=false;let state=load();
function load(){try{return JSON.parse(localStorage.getItem(SKEY))||{students:{},paused:false,broadcast:''}}catch{return{students:{},paused:false,broadcast:''}}}
function save(){localStorage.setItem(SKEY,JSON.stringify(state))}function show(id){['home','student','instructor','projector'].forEach(x=>document.getElementById(x).classList.toggle('hidden',x!==id))}function exitToHome(){show('home')}
function joinStudent(){const n=joinName.value.trim();if(!n)return toastMsg('Enter a name or explorer code first.');current=n;if(!state.students[n])state.students[n]={messages:[],last:Date.now(),previousResponseId:null};state.students[n].last=Date.now();save();studentPill.textContent=n;show('student');renderChat();applyPause();setTimeout(()=>promptBox.focus(),50)}
function welcomeHTML(){return `<div id="welcome" class="welcome"><div class="spark">✦</div><h2>How can I help you today?</h2><p>Ask a question, build an idea, write something, or keep exploring.</p><div class="chips"><button class="chip" onclick="prefill('Explain something interesting to me')">✨ Explain something</button><button class="chip" onclick="prefill('Help me create a story')">✍️ Create a story</button><button class="chip" onclick="prefill('I have an idea. Help me improve it')">💡 Improve an idea</button></div></div>`}
function renderChat(){thread.innerHTML='';const data=state.students[current];if(!data||!data.messages.length){thread.innerHTML=welcomeHTML();return}data.messages.forEach(m=>addBubble(m.role,m.text,m.imageUrl,false));scrollDown()}
function escapeHTML(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderMarkdown(text){let s=escapeHTML(text);s=s.replace(/```([\s\S]*?)```/g,'<pre><code>$1</code></pre>');s=s.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>');s=s.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');const lines=s.split('\n');let out='',list=null;for(const line of lines){if(/^[-*] /.test(line)){if(list!=='ul'){if(list)out+=`</${list}>`;out+='<ul>';list='ul'}out+='<li>'+line.replace(/^[-*] /,'')+'</li>'}else if(/^\d+\. /.test(line)){if(list!=='ol'){if(list)out+=`</${list}>`;out+='<ol>';list='ol'}out+='<li>'+line.replace(/^\d+\. /,'')+'</li>'}else{if(list){out+=`</${list}>`;list=null}if(line.trim()&&!/^<h[1-3]>/.test(line))out+='<p>'+line+'</p>';else out+=line}}if(list)out+=`</${list}>`;return out}
function addBubble(role,text,imageUrl=null,saveIt=true){document.getElementById('welcome')?.remove();const d=document.createElement('div');d.className='msg '+(role==='user'?'user':'');d.innerHTML=(role==='ai'?'<div class="avatar">✦</div>':'')+'<div class="bubble"></div>';const b=d.querySelector('.bubble');if(role==='ai'){b.classList.add('assistant-content');b.innerHTML=renderMarkdown(text||'')}else b.textContent=text||'';if(imageUrl){const img=document.createElement('img');img.src=imageUrl;img.alt='AI generated image';img.className='generated-image';b.appendChild(img)}thread.appendChild(d);if(saveIt&&current){state.students[current].messages.push({role,text,imageUrl,time:Date.now()});state.students[current].last=Date.now();save()}scrollDown()}
function addTyping(){const d=document.createElement('div');d.id='typing';d.className='msg';d.innerHTML='<div class="avatar">✦</div><div class="bubble"><span class="typing"><i></i><i></i><i></i></span></div>';thread.appendChild(d);scrollDown()}
function prefill(t){promptBox.value=t;resizeBox(promptBox);promptBox.focus()}function resizeBox(el){el.style.height='auto';el.style.height=Math.min(el.scrollHeight,150)+'px'}function handleKey(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}}
async function sendMessage(){if(busy||state.paused)return;if(state.broadcast){addBubble('ai',state.broadcast);state.broadcast='';save()}const t=promptBox.value.trim();if(!t)return;const wantsImage=imageNext;imageNext=false;imageBtn.classList.remove('active');promptBox.placeholder='Message AI360…';promptBox.value='';resizeBox(promptBox);addBubble('user',t);busy=true;sendBtn.disabled=true;addTyping();try{const student=state.students[current];const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:t,studentId:current,previousResponseId:student.previousResponseId||null,wantsImage})});const data=await r.json();document.getElementById('typing')?.remove();if(!r.ok)throw new Error(data.error||'AI request failed');if(data.responseId){student.previousResponseId=data.responseId;save()}addBubble('ai',data.text||(data.imageUrl?'Here you go! 🎨':''),data.imageUrl||null)}catch(e){document.getElementById('typing')?.remove();const msg=/credit|quota|429/i.test(e.message)?'AI360 is temporarily unavailable because the club API credits need attention. Please tell your instructor.':'I couldn’t connect to AI360 right now. Please tell your instructor and try again.';addBubble('ai',msg);console.error(e)}finally{busy=false;sendBtn.disabled=false;promptBox.focus()}}
function imageMode(){imageNext=!imageNext;imageBtn.classList.toggle('active',imageNext);promptBox.placeholder=imageNext?'Describe the image you want…':'Message AI360…';promptBox.focus()}function clearChat(){if(!current)return;if(confirm('Start a new chat?')){state.students[current].messages=[];state.students[current].previousResponseId=null;save();renderChat();promptBox.focus()}}
function applyPause(){composerWrap.classList.toggle('paused',state.paused);promptBox.disabled=state.paused;promptBox.placeholder=state.paused?'Chat paused by instructor':'Message AI360…'}function openInstructor(){show('instructor');renderInstructor()}function renderInstructor(){const entries=Object.entries(state.students);statStudents.textContent=entries.length;statMessages.textContent=entries.reduce((a,[,v])=>a+v.messages.length,0);statMode.textContent=state.paused?'Paused':'Open';pauseBtn.textContent=state.paused?'▶ Resume chat':'⏸ Pause chat';studentsGrid.innerHTML=entries.length?entries.sort((a,b)=>b[1].last-a[1].last).map(([n,v])=>`<div class="student-card" onclick="viewStudent('${esc(n)}')"><span class="dot"></span><b>${html(n)}</b><br><span class="tiny">${v.messages.length} messages · ${ago(v.last)}</span></div>`).join(''):'<p class="tiny">No explorers have joined yet.</p>'}
function viewStudent(n){const v=state.students[n];drawerTitle.textContent=n;drawerLogs.innerHTML=v.messages.length?v.messages.map(m=>`<div class="log"><b>${m.role==='user'?'Explorer':'AI360'}</b><br>${html(m.text||'')}${m.imageUrl?'<br>🎨 Generated image':''}</div>`).join(''):'<p class="tiny">No messages yet.</p>';drawer.classList.remove('hidden')}function togglePause(){state.paused=!state.paused;save();renderInstructor();toastMsg(state.paused?'Chat paused.':'Chat resumed.')}function broadcast(msg){state.broadcast=msg;save();projectorAlert.textContent=msg;projectorAlert.classList.remove('hidden');toastMsg('Class message prepared.')}function resetSession(){if(confirm('Delete all local test data?')){state={students:{},paused:false,broadcast:''};save();renderInstructor();toastMsg('Test data reset.')}}function openProjector(){show('projector');if(state.broadcast){projectorAlert.textContent=state.broadcast;projectorAlert.classList.remove('hidden')}else projectorAlert.classList.add('hidden')}function toastMsg(t){toast.textContent=t;toast.classList.remove('hidden');setTimeout(()=>toast.classList.add('hidden'),2200)}function scrollDown(){setTimeout(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'}),20)}function ago(ts){const m=Math.floor((Date.now()-ts)/60000);return m<1?'just now':m+' min ago'}function html(s){return escapeHTML(s)}function esc(s){return String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
joinName.addEventListener('keydown',e=>{if(e.key==='Enter')joinStudent()});
