const $=s=>document.querySelector(s);
const conversation=$('#conversation'),messagesEl=$('#messages'),welcome=$('#welcome'),input=$('#messageInput'),composer=$('#composer'),sendButton=$('#sendButton'),imageButton=$('#imageButton'),historyEl=$('#chatHistory');
let wantsImage=false;
let profile=JSON.parse(localStorage.getItem('ai360_profile')||'{"name":"Hanin","group":"general"}');
let chats=JSON.parse(localStorage.getItem('ai360_chats')||'[]');
let activeId=localStorage.getItem('ai360_active_chat')||null;
if(!activeId||!chats.some(c=>c.id===activeId)) createChat(false);
applyProfile();renderHistory();renderChat();

function createChat(render=true){const chat={id:crypto.randomUUID(),title:'New chat',messages:[],previousResponseId:null,createdAt:Date.now()};chats.unshift(chat);activeId=chat.id;save();if(render){renderHistory();renderChat();input.focus()}return chat}
function activeChat(){return chats.find(c=>c.id===activeId)}
function save(){localStorage.setItem('ai360_chats',JSON.stringify(chats.slice(0,30)));localStorage.setItem('ai360_active_chat',activeId)}
function escapeHtml(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function markdown(text=''){let s=escapeHtml(text);s=s.replace(/```([\s\S]*?)```/g,'<pre><code>$1</code></pre>');s=s.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>');s=s.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');const lines=s.split('\n');let out='',list=null;for(const line of lines){let m=line.match(/^\s*[-*] (.+)$/);let n=line.match(/^\s*\d+\. (.+)$/);if(m||n){const type=m?'ul':'ol';if(list!==type){if(list)out+=`</${list}>`;out+=`<${type}>`;list=type}out+=`<li>${m?m[1]:n[1]}</li>`}else{if(list){out+=`</${list}>`;list=null}if(line.trim()&&!/^<(h\d|pre)/.test(line))out+=`<p>${line}</p>`;else out+=line}}if(list)out+=`</${list}>`;return out}
function renderHistory(){historyEl.innerHTML='';for(const c of chats){const b=document.createElement('button');b.className='history-item'+(c.id===activeId?' active':'');b.textContent=c.title;b.onclick=()=>{activeId=c.id;save();renderHistory();renderChat()};historyEl.appendChild(b)}}
function renderChat(){const c=activeChat();$('#chatTitle').textContent=c.title;messagesEl.innerHTML='';welcome.style.display=c.messages.length?'none':'block';for(const m of c.messages)addMessageDom(m,false);requestAnimationFrame(()=>conversation.scrollTop=conversation.scrollHeight)}
function addMessageDom(m,scroll=true){const row=document.createElement('div');row.className='message '+m.role;if(m.role==='assistant'){const icon=document.createElement('div');icon.className='ai-icon';icon.textContent='✦';row.appendChild(icon)}const bubble=document.createElement('div');bubble.className='bubble';bubble.innerHTML=m.role==='assistant'?markdown(m.text):escapeHtml(m.text);if(m.imageUrl){const img=document.createElement('img');img.src=m.imageUrl;img.className='image-result';img.alt='AI-generated image';bubble.appendChild(img)}row.appendChild(bubble);messagesEl.appendChild(row);if(scroll)requestAnimationFrame(()=>conversation.scrollTop=conversation.scrollHeight);return row}
function setTyping(on){const old=$('#typingRow');if(old)old.remove();if(!on)return;const row=document.createElement('div');row.id='typingRow';row.className='message assistant';row.innerHTML='<div class="ai-icon">✦</div><div class="bubble"><span class="typing"><i></i><i></i><i></i></span></div>';messagesEl.appendChild(row);conversation.scrollTop=conversation.scrollHeight}
function autosize(){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,180)+'px'}input.addEventListener('input',autosize);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();composer.requestSubmit()}});
$('#newChat').onclick=()=>createChat();
imageButton.onclick=()=>{wantsImage=!wantsImage;imageButton.classList.toggle('active',wantsImage);imageButton.innerHTML=wantsImage?'<span>◉</span> Image on':'<span>◉</span> Image';input.focus()};
composer.addEventListener('submit',async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;const c=activeChat();c.messages.push({role:'user',text});if(c.messages.length===1)c.title=text.length>34?text.slice(0,34)+'…':text;input.value='';autosize();welcome.style.display='none';renderHistory();addMessageDom(c.messages.at(-1));save();sendButton.disabled=true;setTyping(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,previousResponseId:c.previousResponseId,wantsImage,gradeGroup:profile.group})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');c.previousResponseId=data.responseId||c.previousResponseId;const reply={role:'assistant',text:data.text||((data.imageUrl)?'Here you go.':'I’m here — try asking that another way.'),imageUrl:data.imageUrl||null};c.messages.push(reply);setTyping(false);addMessageDom(reply);save()}catch(err){setTyping(false);const reply={role:'assistant',text:'I couldn’t complete that request right now. Please try again in a moment.'};c.messages.push(reply);addMessageDom(reply);save();console.error(err)}finally{sendButton.disabled=false;wantsImage=false;imageButton.classList.remove('active');imageButton.innerHTML='<span>◉</span> Image';input.focus()}});
function applyProfile(){$('#profileName').textContent=profile.name;$('#avatar').textContent=(profile.name||'A')[0].toUpperCase();$('#profileGroup').textContent=profile.group==='grades12'?'Grades 1–2':profile.group==='grades35'?'Grades 3–5':'AI360 member';$('#nameSetting').value=profile.name;$('#groupSetting').value=profile.group}
$('#profileButton').onclick=()=>$('#profileDialog').showModal();$('#saveProfile').onclick=e=>{e.preventDefault();profile={name:$('#nameSetting').value.trim()||'Student',group:$('#groupSetting').value};localStorage.setItem('ai360_profile',JSON.stringify(profile));applyProfile();$('#profileDialog').close()};
$('#openSidebar').onclick=()=>{$('#sidebar').classList.add('open');$('#sidebarScrim').classList.add('show')};function closeSide(){$('#sidebar').classList.remove('open');$('#sidebarScrim').classList.remove('show')}$('#closeSidebar').onclick=closeSide;$('#sidebarScrim').onclick=closeSide;
